CREATE TABLE Users (
    ID           INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME         TEXT    NOT NULL,
    LAST_NAME    TEXT    NOT NULL,
    BIRTH_DATE   DATE,
    USERNAME     TEXT    NOT NULL UNIQUE,
    EMAIL        TEXT    NOT NULL UNIQUE,
    PASSWORD     TEXT    NOT NULL,
    GUILD_ID     INTEGER
);

CREATE TABLE Tokens (
    ID            INTEGER  PRIMARY KEY AUTOINCREMENT,
    TOKEN         TEXT     NOT NULL,
    TOKEN_CREATED DATETIME NOT NULL
);
